# Generated by Django 5.1.2 on 2024-10-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0002_taskfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
